spring:
  cloud:
    stream:
      bindings:
        transformacionSubscribableChannel:
          destination: conectorEntradaMessages
          group: transformacionjsonxmlQueue
        transformacionMessagesChannel:
          destination: transformacionjsonxmlMessages
        transformacionMessagesChannelErrores:
          destination: replayMessages
                    