spring:
  rabbitmq:
    host: broker-rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        transformacionSubscribableChannel:
          destination: conectorEntradaMessages
          group: transformacionjsonxmlQueue
        transformacionMessagesChannel:
          destination: transformacionjsonxmlMessages
        transformacionMessagesChannelErrores:
          destination: replayMessages
                    