spring:
  rabbitmq:
    host: broker
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        transformacionSubscribableChannel:
          destination: conectorSalidaMessages
          group: transformacionxmljsonQueue
        transformacionMessagesChannel:
          destination: replayMessages